export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SOLICITAR_REDEFINICAO_SENHA = "SOLICITAR_REDEFINICAO_SENHA";
export const SOLICITAR_REDEFINICAO_SENHA_SUCCESS = "SOLICITAR_REDEFINICAO_SENHA_SUCCESS";

export const RESETAR_SENHA = "RESETAR_SENHA";
export const RESETAR_SENHA_SUCCESS = "RESETAR_SENHA_SUCCESS";

export const LOGOUT = "LOGOUT";