export const EFETUAR_RESGATE = "EFETUAR_RESGATE";
export const EFETUAR_RESGATE_SUCCESS = "EFETUAR_RESGATE_SUCCESS";

export const EXIBIR_MODAL_RESGATE = "EXIBIR_MODAL_RESGATE";
export const ESCONDER_MODAL_RESGATE = "ESCONDER_MODAL_RESGATE";

export const EXIBIR_BOTOES_CONFIRMAR = "EXIBIR_BOTOES_CONFIRMAR";
export const ESCONDER_BOTOES_CONFIRMAR = "ESCONDER_BOTOES_CONFIRMAR";