export const CADASTRAR_CLIENTE = "CADASTRAR_CLIENTE";
export const CADASTRAR_CLIENTE_SUCCESS = "CADASTRAR_CLIENTE_SUCCESS";

export const EXIBIR_MODAL_EDITAR_CLIENTE = "EXIBIR_MODAL_EDITAR_CLIENTE";
export const ESCONDER_MODAL_EDITAR_CLIENTE = "ESCONDER_MODAL_EDITAR_CLIENTE";

export const OBTER_DADOS_USUARIO = "OBTER_DADOS_USUARIO";
export const OBTER_DADOS_USUARIO_SUCCESS = "OBTER_DADOS_USUARIO_SUCCESS";

export const ATUALIZAR_CLIENTE = "ATUALIZAR_CLIENTE";
export const ATUALIZAR_CLIENTE_SUCCESS = "ATUALIZAR_CLIENTE_SUCCESS";