export const OBTER_PONTUACOES = "OBTER_PONTUACOES";
export const OBTER_PONTUACOES_SUCCESS = "OBTER_PONTUACOES_SUCCESS";

export const DEFINIR_DADOS_PONTUACAO = "DEFINIR_DADOS_PONTUACAO";
export const LIMPAR_DADOS_PONTUACAO = "LIMPAR_DADOS_PONTUACAO";