export const OBTER_PONTUACOES = "OBTER_PONTUACOES";
export const OBTER_PONTUACOES_SUCCESS = "OBTER_PONTUACOES_SUCCESS";

export const DEFINIR_DADOS_PONTUACAO = "DEFINIR_DADOS_PONTUACAO";
export const LIMPAR_DADOS_PONTUACAO = "LIMPAR_DADOS_PONTUACAO";

export const OBTER_HISTORICO_PONTUACAO_CLIENTE_POR_ESTABELECIMENTO = "OBTER_HISTORICO_PONTUACAO_CLIENTE_POR_ESTABELECIMENTO";
export const OBTER_HISTORICO_PONTUACAO_CLIENTE_POR_ESTABELECIMENTO_SUCCESS = "OBTER_HISTORICO_PONTUACAO_CLIENTE_POR_ESTABELECIMENTO_SUCCESS";

export const OBTER_PONTUACAO_CLIENTE_COMPLETA = "OBTER_PONTUACAO_CLIENTE_COMPLETA";
export const OBTER_PONTUACAO_CLIENTE_COMPLETA_SUCCESS = "OBTER_PONTUACAO_CLIENTE_COMPLETA_SUCCESS";